const axios = require("axios");
const { cmd } = require('../command');

cmd({
  pattern: "ss1",
  alias: ["ssweb1"],
  react: "🚀",
  desc: "Download screenshot of a given link.",
  category: "other",
  use: ".ss <link>",
  filename: __filename,
}, 
async (conn, mek, m, { from, reply, q }) => {
  if (!q) {
    return reply("Please provide a URL to capture a screenshot.");
  }

  try {
    // Fetch the screenshot from the API
    const response = await axios.get(`https://bk9.fun/tools/screenshot?device=tablet&url=${encodeURIComponent(q)}`);
    
    // Check if the response contains a valid screenshot URL
    if (!response.data || !response.data.screenshotUrl) {
      return reply("Failed to capture the screenshot. The API did not return a valid URL.");
    }

    const screenshotUrl = response.data.screenshotUrl;

    // Send the screenshot as an image message
    await conn.sendMessage(from, {
      image: { url: screenshotUrl },
      caption: "*SUBZERO SCREENSHOT WEB*\n\n> *© Generated By Subzero ⭐*",
      contextInfo: {
        mentionedJid: [m.sender],
        forwardingScore: 999,
        isForwarded: true,
        forwardedNewsletterMessageInfo: {
          newsletterJid: '120363304325601080@newsletter',
          newsletterName: "Mr Frank OFC",
          serverMessageId: 143,
        },
      },
    }, { quoted: m });

  } catch (error) {
    console.error("Error:", error); // Log the error for debugging
    reply("Failed to capture the screenshot. Please try again.");
  }
});
